var English_words=[
    "apple",
    "blink",
    "chess",
    "daisy",
    "earth",
    "fairy",
    "globe",
    "haste",
    "inbox",
    "jumbo",
    "kayak",
    "laser",
    "mango",
    "noble",
    "oasis",
    "piano",
    "quiet",
    "risky",
    "sugar",
    "tango",
    "ultra",
    "vocal",
    "waltz",
    "xerox",
    "yacht",
    "zebra",
    "abide",
    "baked",
    "caged",
    "dared",
    "eager",
    "fable",
    "gains",
    "hatch",
    "ideal",
    "jolly",
    "kudos",
    "lucky",
    "magic",
    "noble",
    "olive",
    "peace",
    "quake",
    "rider",
    "sable",
    "table",
    "umbra",
    "valid",
    "waste",
    "xenon"
];
function randomWord(){
    return English_words[Math.floor(Math.random()*English_words.length)];

}
export {randomWord};